### ISSUE TITLE
wxGraphicsPath

### ISSUE THREAD

**Issue by HarrievG** [pkulchenko/wxlua#3]
Hi !
 I want to use wxGraphicsPath in WxLua. 
Can we add those bindings here?

If you do not have the time, i am open to doing it myself if given a example on howto build wxLua for zerobrane.

With kind regards,

**Comment by pkulchenko** [comment]
@HarrievG, you can definitely give it a try. I think I've attempted to convert wxGraphicsPath and it had too many dependencies that needed to be taken care of, so it wasn't worth it for me, but with a bit more effort it may be doable.

Here is what you'd need to do.

1. Get a snapshot of wxlua from wxwidgets311 branch.
2. Get snapshot of wxwidgets from https://github.com/pkulchenko/wxwidgets (I recommend this snapshot only because the wxwidgets master branch may have some other changes that may break what's already working). You will only need `interface` folder and nothing else from wxwidgets.
3. Move `wxwidgets` folder next to `wxlua` folder that is the clone of this repository (it will have `wxLua` folder inside of it). This is the default path in the script you will be using, but you can also provide the paths to the script if you have some other configuration.
4. Open the script `wxLua/bindings/any-bind-sync.lua` and update the `steps` table to add `wxGraphicsPath` to it. I'm not sure what file it should go into (since it's not present in wxlua right not), but let's say we put it into `wxcore_gdi`:

```diff
diff --git a/wxLua/bindings/any-bind-sync.lua b/wxLua/bindings/any-bind-sync.lua
index 74fb6ed..4a663c0 100644
--- a/wxLua/bindings/any-bind-sync.lua
+++ b/wxLua/bindings/any-bind-sync.lua
@@ -61,6 +61,7 @@ local steps = {
     wxCaret = "caret.h",
     wxDisplay = "display.h",
     wxBitmap = "bitmap.h",
+    wxGraphicsPath = "graphics.h",
   },
   wxaui_aui = {
     wxAuiToolBarItem = "aui/auibar.h",
```

The script will then find wxGprahicsPath in that file, extract its definition and add it to `wxcore_gdi.i` file in `wxwidgets/` folder.

5. Run `genwxbind.bat` file from `wxLua/bindings` folder; this will generate bindings (actual C++ code) from the interface file that was just updated. This step may generate some errors as it does some checks and it's possible that some of the dependencies are not satisfied (for example, `wxGrapchicsPath` depends on `wxGraphicsObject`, which is not present in wxlua either). You will need to address and resolve those errors to continue.

If everything goes well here, you can then try to compile the update version of wxlua do build wx.dll to use in the IDE. The IDE provides `build/build-win32.sh` script that builds the library from everything you need and puts it in the right place for the IDE to find it. Since it retrieves wxwidgets and wxlua from their repositories,  you will want to comment that out if you want to use your own copy of wxlua and you will want to comment out the lines that remove the repositories after everything is done (since you will be running it multiple times; otherwise your changes and retrieved wxwidgets code will be removed).

Here are the changes you'd need to do:

```diff
diff --git a/build/build-win32.sh b/build/build-win32.sh
index 399f4a3..65a6548 100644
--- a/build/build-win32.sh
+++ b/build/build-win32.sh
@@ -256,12 +256,12 @@ if [ $BUILD_WXWIDGETS ]; then
   make $MAKEFLAGS || { echo "Error: failed to build wxWidgets"; exit 1; }
   make install
   cd ..
-  rm -rf "$WXWIDGETS_BASENAME"
+#  rm -rf "$WXWIDGETS_BASENAME"
 fi
 
 # build wxLua
 if [ $BUILD_WXLUA ]; then
-  git clone "$WXLUA_URL" "$WXLUA_BASENAME" || { echo "Error: failed to get wxWidgets"; exit 1; }
+#  git clone "$WXLUA_URL" "$WXLUA_BASENAME" || { echo "Error: failed to get wxWidgets"; exit 1; }
   cd "$WXLUA_BASENAME/wxLua"
   git checkout wxwidgets311
 
@@ -297,7 +297,7 @@ if [ $BUILD_WXLUA ]; then
   [ -f "$INSTALL_DIR/bin/libwx.dll" ] || { echo "Error: libwx.dll isn't found"; exit 1; }
   [ $DEBUGBUILD ] || strip --strip-unneeded "$INSTALL_DIR/bin/libwx.dll"
   cd ../..
-  rm -rf "$WXLUA_BASENAME"
+#  rm -rf "$WXLUA_BASENAME"
 fi
 
 # build LuaSocket
```

You can then run the following command from the `build` folder: `bash build-win32.sh lua wxwidgets wxlua`. You will need to have mingw installed, but all other dependencies will be retrieved by the script. After the first run, you will want to comment out `git clone` command for wxwidgets as well as you will already have it available, but you won't need to re-compile it anymore and all subsequent runs (after you update wxlua code) will only require running `bash build-win32.sh wxlua`.

**Comment by HarrievG** [comment]
Hi Paul!

Thank you for the detailed response!
It looks that there are some caveats with this, and since i found a work around for my problem there is no need for me to attempt this.

(i need splines, and it you can do that just fine in wxLua with :
```
frame = wx.wxFrame(wx.NULL, wx.wxID_ANY, "wxLua Minimal Demo",
                   wx.wxDefaultPosition, wx.wxSize(450, 450),
                   wx.wxDEFAULT_FRAME_STYLE)
local dc = wx.wxPaintDC(frame)
dc.DrawSpline(dc,{{10,20},{10,40},{50,60}}) 
```
Thanks again , with the info in this post maybe someone else can pick this up, or i might try again in the future,

With kind regards,

**Comment by pkulchenko** [comment]
@HarrievG, FYI, this was added in 29bc38e4 and is in the master branch already.

**Comment by HarrievG** [comment]
Hey!

Thanks for letting me know!!

Happy deving :)

With kind regards,
Harrie van Ginneken.
