### ISSUE TITLE
wxListCtrl background draw in MSW

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/wxlua#30]
According to
https://forums.wxwidgets.org/viewtopic.php?t=44320

the problem with wxListCtrl drawing should be solved by setting manifest in MSW.
But can wx.dll include a manifest?
How should be done?

**Comment by sonoro1234** [comment]
Opened wx.dll with notepad and found the manifest on it, but I still have this wxListCtrl draw problem.

**Comment by pkulchenko** [comment]
@sonoro1234, I think it's because the executable has the manifest. It's in `zbstudio/res/zbstudio.manifest` which gets included in `zbstudio/res/zbstudio.rc`, which is then used in `build-win32.sh` when building the launcher.

I don't think the manifest can be included in the dynamic library (or be useful if included), as the manifest is recognized when the executable is loaded.

**Comment by sonoro1234** [comment]
But
1- I checked that the manifest is included in my wx.dll and ZeroBraneStudio wx.dll
2- I tested ZeroBraneStudio wx.dll with LuaJIT.exe and it did work correctly in wxListCtrl draw (not my wx.dll)

**Comment by pkulchenko** [comment]
Maybe there is something else (other than the manifest) involved? You can take the working library and replace its manifest with yours and also test your library with the same manifest as exists in the working one to see which combinations are working. You can [replace the manifest using mt.exe](https://docs.microsoft.com/en-us/windows/desktop/SbsCs/mt-exe). I think it should give you all the information you need (or at least confirm if it's something in the binary code, rather than the manifest).

**Comment by sonoro1234** [comment]
Extracted manifests with mt.exe and they are equal

**Comment by pkulchenko** [comment]
Then it has something to do with (1) the code in wx.dll or (2) the executable you are loading it with. If the executable is the same, then the difference in the behavior is caused by the code itself and not the manifest.

**Comment by sonoro1234** [comment]
Yes, it seems so.
The main difference between my wx.dll and ZeroBrane wx.dll is the wxWidgets it uses.
There are also some differences in wxLua code because you use branch WX_3_1_0-7d9d59 instead of your last wxwidgets311 branch

**Comment by pkulchenko** [comment]
One other thing to consider is the Windows DLLs that wx.dll is linked against. You may want to use [dependency walker](http://www.dependencywalker.com/) to see what DLLs the two versions of wx.dll are linked against.

**Comment by sonoro1234** [comment]
Lot of dlls.
They seem the same but sometimes in a different level (LIBGCC_S_DW2-1.DLL is not in your first level of dependency but it is loaded by LUA51.dll while in my executable it is in the first level of loading)

I had to add "-lversion;-lshlwapi;-luxtheme;-loleacc;-lws2_32" to succeed in the cmake build but this dlls also appear in your wx.dll dependency graph not as first level but being loaded by other first level dlls

**Comment by pkulchenko** [comment]
This issue was fixed in https://trac.wxwidgets.org/ticket/18441.
