### ISSUE TITLE
[win] Handles leak on wxFileSystemWatcher

### ISSUE THREAD

**Issue by moteus** [pkulchenko/wxlua#52]
Seems that wxFileSystemWatcher:remove method keeps file handle open.
I test it on windows with ZBS
```
ZeroBrane Studio (devel; MobDebug 0.705)
Copyright © 2011-2019 ZeroBrane LLC
Paul Kulchenko
Licensed under the MIT License. 
Built with wxWidgets 3.1.3, wxLua 3.0.0.3, Scintilla 3.7.2
```

Basic example 
```Lua
local wx = require "wx"

local frame = wx.wxFrame(wx.NULL, -1, "Title")

local watcher = wx.wxFileSystemWatcher()

watcher:SetOwner(frame)

for _ = 1,10 do
    local p = wx.wxFileName.DirName("d:\\installs")
    watcher:Add(p, wx.wxFSW_EVENT_CREATE + wx.wxFSW_EVENT_DELETE + wx.wxFSW_EVENT_RENAME)
    watcher:Remove(p)
end

frame:Show()

wx.wxGetApp():MainLoop()
```
Process explorer shows 10 file handles pointed to `d:\installs` directory.

**Comment by pkulchenko** [comment]
@moteus, thank you for the report. I wonder if this is related to [17867](https://trac.wxwidgets.org/ticket/17867) ticket I opened some time ago, as the symptoms are similar.

By looking at the wxwidgets source code `:Remove` call doesn't actually remove the watcher, as it only sets it for removal, which is then supposed to be removed when `CompleteRemoval` is called, but I'll have to check when the latter call is triggered in wxwidgets:

```
    // Removes a watch we're currently using. Notice that this doesn't happen
    // immediately, CompleteRemoval() must be called later when it's really
    // safe to delete the watch, i.e. after completion of the IO operation
    // using it.
    bool ScheduleForRemoval(const wxSharedPtr<wxFSWatchEntryMSW>& watch)
....

    // Really remove the watch previously passed to ScheduleForRemoval().
    //
    // It's ok to call this for a watch that hadn't been removed before, in
    // this case we'll just return false and do nothing.
    bool CompleteRemoval(wxFSWatchEntryMSW* watch)
```

It seems that CompleteRemoval is only called in one place: when the same watcher gets a new event associated with it, which seems like it hasn't yet happened in your case (which is why I think it may be similar/related to the ticket I referenced).

Can you try creating/deleting something in that folder after the loop is over and then check if the number of allocated handles stays the same?

I'll check with wxwidgets maillist if this is intentional or not.

> Process explorer shows 10 file handles pointed to d:\installs directory.

Are you using this process explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer?

**Comment by moteus** [comment]
>Can you try creating/deleting something in that folder after the loop is over and then check if the number of allocated handles stays the same?

I can confirm that in this case all handlers closed.

>Are you using this process explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer?

Yes. It can shows all opened handlers for the specific process.

**Comment by pkulchenko** [comment]
> I can confirm that in this case all handlers closed.

Ok, so the actual removal works, but it's only triggered after at least one new event arrives for the same watcher.

I posted a message to the wxwidgets maillist (https://groups.google.com/forum/#!topic/wx-dev/VsK-YibZw0U) asking for details on this behavior.

**Comment by pkulchenko** [comment]
Given the [discussion I referenced](https://groups.google.com/forum/#!topic/wx-dev/VsK-YibZw0U), there is not much I can do in the IDE, so I'll close this ticket, but will update when there are any updates to this `wxFileSystemWatcher` behavior.
