### ISSUE TITLE
Can upload a compile completed windows can use it?

### ISSUE THREAD

**Issue by ashi876** [pkulchenko/wxlua#6]
I'm a beginner
The government has not released it for a long time
Can upload a compile completed windows64bit can use it?

thanks

**Comment by pkulchenko** [comment]
I don't plan to provide binaries for windows 64bit, but I have scripts that compile wxlua, wxwidgets and all the dependencies, so if you set up open source development environment on Windows using msys2/gcc, you can compile those libraries yourself using [this script](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/build/build-macosx.sh).

Since it may be a bit complicated if you are starting, you can use the binaries already included with [ZeroBraneStudio IDE](https://github.com/pkulchenko/ZeroBraneStudio/), which is using wxlua. The binaries are 32bit, but you should still be able to run them on all Windows versions.
